### ISSUE TITLE
FYI SPEW

### ISSUE THREAD

**Issue by rikkimax** [Straivers/Oswald#1]
Hey.

I was just made aware your work.
Just an FYI about [SPEW](https://github.com/Devisualization/spew).

Not ready for users and so hence not on code.dlang.org.
Much more heavy weight, but may interest you.

**Comment by david7a68** [comment]
Thanks.

Oswald is predominantly a learning project, and is designed to create windows and nothing else. SPEW is (as you said) far too heavyweight for what I want to do with Oswald. I am definitely very interested though.
